server:
  port: 9102

spring:
  application:
    name: micront-printing
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
